"""Small source-gamut and animation fixtures, outside the application checkout.

The fixture ICC profiles are generated by Little CMS, using standard encoding
parameters rather than redistributing a third-party profile binary.
Display P3: https://registry.color.org/rgb-registry/displayp3
Adobe RGB: https://www.adobe.com/digitalimag/pdfs/AdobeRGB1998.pdf
"""
import argparse
import ctypes as c
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageCms

parser = argparse.ArgumentParser()
parser.add_argument('--output-dir', type=Path, default=Path('E:/picakeep-image-pipeline-022-fixtures'))
parser.add_argument('--lcms-library', default='D:/Anaconda3/Library/bin/lcms2.dll')
args = parser.parse_args()
args.output_dir.mkdir(parents=True, exist_ok=True)
library = c.CDLL(args.lcms_library)

class Chromaticity(c.Structure):
    _fields_ = [('x', c.c_double), ('y', c.c_double), ('Y', c.c_double)]
class Primaries(c.Structure):
    _fields_ = [('red', Chromaticity), ('green', Chromaticity), ('blue', Chromaticity)]

library.cmsBuildGamma.argtypes = [c.c_void_p, c.c_double]
library.cmsBuildGamma.restype = c.c_void_p
library.cmsBuildParametricToneCurve.argtypes = [c.c_void_p, c.c_int32, c.POINTER(c.c_double)]
library.cmsBuildParametricToneCurve.restype = c.c_void_p
library.cmsCreateRGBProfile.argtypes = [c.POINTER(Chromaticity), c.POINTER(Primaries), c.POINTER(c.c_void_p)]
library.cmsCreateRGBProfile.restype = c.c_void_p
library.cmsSaveProfileToMem.argtypes = [c.c_void_p, c.c_void_p, c.POINTER(c.c_uint32)]
library.cmsCloseProfile.argtypes = [c.c_void_p]
library.cmsFreeToneCurve.argtypes = [c.c_void_p]
library.cmsGetEncodedCMMversion.restype = c.c_uint32

def make_profile(kind):
    if kind == 'p3':
        coordinates = [(.68, .32), (.265, .69), (.15, .06)]
        params = (c.c_double * 5)(2.4, 1 / 1.055, .055 / 1.055, 1 / 12.92, .04045)
        curve = library.cmsBuildParametricToneCurve(None, 4, params)
    else:
        coordinates = [(.64, .33), (.21, .71), (.15, .06)]
        curve = library.cmsBuildGamma(None, 2.19921875)
    assert curve
    white = Chromaticity(.3127, .329, 1)
    primary = Primaries(*[Chromaticity(x, y, 1) for x, y in coordinates])
    profile = library.cmsCreateRGBProfile(c.byref(white), c.byref(primary), (c.c_void_p * 3)(curve, curve, curve))
    assert profile
    try:
        length = c.c_uint32()
        assert library.cmsSaveProfileToMem(profile, None, c.byref(length))
        raw = c.create_string_buffer(length.value)
        assert library.cmsSaveProfileToMem(profile, raw, c.byref(length))
        ImageCms.ImageCmsProfile(__import__('io').BytesIO(raw.raw))
        return raw.raw
    finally:
        library.cmsCloseProfile(profile)
        library.cmsFreeToneCurve(curve)

pixels = np.zeros((960, 640, 3), dtype=np.uint8)
patches = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0),
           (0, 255, 255), (255, 0, 255), (128, 128, 128), (64, 192, 32)]
for i, rgb in enumerate(patches):
    row, column = divmod(i, 2)
    pixels[row * 240:(row + 1) * 240, column * 320:(column + 1) * 320] = rgb
image = Image.fromarray(pixels)
outputs = []
for kind in ['p3', 'adobe-rgb']:
    path = args.output_dir / f'640x960-{kind}-icc.png'
    image.save(path, icc_profile=make_profile(kind))
    outputs.append(path)
first = Image.new('RGB', (16, 16), (240, 10, 20))
second = Image.new('RGB', (16, 16), (10, 220, 30))
for suffix in ['gif', 'webp']:
    path = args.output_dir / f'16x16-two-frame.{suffix}'
    first.save(path, save_all=True, append_images=[second], duration=[120, 180], loop=0,
               **({'lossless': True} if suffix == 'webp' else {}))
    with Image.open(path) as verification:
        assert verification.n_frames == 2
        verification.seek(0); a = verification.convert('RGBA').tobytes()
        verification.seek(1); b = verification.convert('RGBA').tobytes()
        assert a != b
    outputs.append(path)
manifest = {
    'littleCmsEncodedVersion': library.cmsGetEncodedCMMversion(),
    'profileParameters': 'D65; Display P3 primaries + sRGB transfer / AdobeRGB1998 primaries + gamma563/256',
    'files': [{'file': p.name, 'bytes': p.stat().st_size,
               'sha256': hashlib.sha256(p.read_bytes()).hexdigest()} for p in outputs],
}
(args.output_dir / 'color-animation-manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
print(json.dumps(manifest, indent=2))
